### ISSUE TITLE
"System.ArgumentOutOfRangeException: Index was out of range" when decompiling HL2 Beta maps

### ISSUE THREAD

**Issue by Equalizer5118** [wfowler1/bsp-decompiler#19]
I am attempting to decompile maps from "[The Thing](https://www.moddb.com/games/half-life-2/addons/the-thing)", which was the first custom campaign for Half-Life 2 built off the leaked beta code, but after attempting to decompile the maps it keeps throwing this error:
```
Exception caught in Job 7: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Decompiler.BSPExtensions.GetLeavesInTree(BSP bsp, Node node)
   at Decompiler.BSPExtensions.GetBrushesInModel(BSP bsp, Model model)
   at Decompiler.BSPDecompiler.ProcessEntity(Entity entity)
   at Decompiler.BSPDecompiler.Decompile()
   at Decompiler.Job.Run()
```

I don't know if I am doing something wrong or if this format is just not supported.

**Comment by wfowler1** [comment]
Fixed by https://github.com/wfowler1/bsp-decompiler/commit/48c43f58b028168271b4a4055d0202e5a29d875d
