### ISSUE TITLE
Support for LZMA compressed lumps for Source Engine

### ISSUE THREAD

**Issue by sdfdger** [wfowler1/bsp-decompiler#20]
```
Exception caught in Job 1: System.ArgumentException: Brace mismatch when parsing entities! Entity: 0 Brace level: 2
   at LibBSP.Entities..ctor(Byte[] data, BSP bsp, LumpInfo lumpInfo)
   at LibBSP.Entity.LumpFactory(Byte[] data, BSP bsp, LumpInfo lumpInfo)
   at LibBSP.BSP.get_Entities()
   at Decompiler.BSPDecompiler..ctor(BSP bsp, Job master)
   at Decompiler.Job.Run()
```

File -> Open as: `Auto`

[pl_badwater.bsp.zip](https://github.com/wfowler1/bsp-decompiler/files/15214563/pl_badwater.bsp.zip)

**Comment by wfowler1** [comment]
The lumps in this file are compressed with LZMA, which isn't supported at the moment. I hesitate to add the LZMA SDK to this project because of potential code licensing issues, but at this point I might just do it.
